version: '3'

services:
  hemppa:
    container_name: hemppa
    image: 'hemppa:latest'
    build: '.'
    restart: always
    environment:
      - MATRIX_ACCESS_TOKEN="{{ hemppatoken }}"
      - MATRIX_USER=@hemppabot:"{{ domain }}"
      - MATRIX_SERVER=https://"{{ domain }}"
      - JOIN_ON_INVITE=True
      - BOT_OWNERS=@igel:jaeger.website
      - DEBUG=False
      - TZ=Europe/Berlin
    volumes:
      - ${PWD}/config/:/bot/config
      - ${PWD}/credentials.json:/bot/credentials.json
      - ${PWD}/token.pickle:/bot/token.pickle

    stop_signal: SIGINT
