version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_CONFIGFILE: "/data/c.toml"
    volumes:
      - "{{ navidromepath }}/data:/data:rw"
      - "{{ navidromepath }}/navidrome.toml:/data/navidrome.toml:rw"
      - "{{ navidromepath }}/music:/music:ro"
