---
#Static Websites
#homepage
- name: Create homepage folder
  file:
    path: "{{ homepagepath }}"
    state: directory

- name: Clone homepage repository
  git:
    repo: https://github.com/Igeljaeger/igel.jaeger.website.git
    dest: "{{ homepagepath }}"
    clone: yes
    update: yes

- name: Recursively change ownership of a homepage directory
  ansible.builtin.file:
    path: "{{ homepagepath }}"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ group }}"

#Stickers
- name: Create Stickers Data Folder
  file:
    path: "{{ stickerspath }}"
    state: directory

- name: Clone Stickerpicker repository
  git:
    repo: https://github.com/Igeljaeger/stickerpicker.git
    dest: "{{ stickerspath }}"
    clone: yes
    update: yes

- name: Recursively change ownership of a Stickers directory
  ansible.builtin.file:
    path: "{{ stickerspath }}"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ group }}"

#Docker
- name: Create homepage folder
  file:
    path: "{{ composepath }}"
    state: directory

- name: Create bibliogram folder
  file:
    path: "{{ bibliogrampath }}"
    state: directory

- name: Clone the bibliogram repository
  git:
    repo: https://git.sr.ht/~cadence/bibliogram
    dest: "{{ bibliogrampath }}"
    clone: yes
    update: yes

- name: Install the package "docker.io"
  apt:
    name: docker.io
    state: present

- name: Install the package "docker-compose"
  apt:
    name: docker-compose
    state: present

- name: Create Navidrome folders
  file:
    path: "{{ navidromepath }}/music"
    state: directory

- name: Copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items:
    - { src: "matrix/config.json", dest: "{{ elementpath }}"}

- name: Sync template folders
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "{{ templatespath }}/docker", dest: "{{ composepath }}" }
    - { src: "{{ templatespath }}/matrix", dest: "{{ synapsepath }}" }
    - { src: "{{ templatespath }}/nginx", dest: "{{ nginxsites }}" }
#run docker-compose up -d in the respective paths (see above and in the vars file for reference)