---
#Nginx
- name: Update repositories cache and install "nginx" package
  apt:
    name: nginx
    update_cache: yes

- name: Copy nginx templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: "root"
    group: "root"
  with_items:
    - { src: "default.j2", dest: "{{ nginx-sites }}/default.nginx"}
    - { src: "insta.j2", dest: "{{ nginx-sites }}/insta.nginx"}
    - { src: "matrix.j2", dest: "{{ nginx-sites }}/matrix.nginx"}
    - { src: "navidrome.j2", dest: "{{ nginx-sites }}/navidrome.nginx"}
    - { src: "reden.j2", dest: "{{ nginx-sites }}/reden.nginx"}
    - { src: "searx.j2", dest: "{{ nginx-sites }}/searx.nginx"}
    - { src: "stickers.j2", dest: "{{ nginx-sites }}/stickers.nginx"}

#Static Websites
#homepage
- name: Create homepage folder
  file:
    path: "{{ homepage-path }}"
    state: directory

- name: Clone a homepage repository
  git:
    repo: https://github.com/Igeljaeger/igel.jaeger.website.git
    dest: "{{ homepage-path }}"
    clone: yes
    update: yes

- name: Recursively change ownership of a homepage directory
  ansible.builtin.file:
    path: "{{ homepage-path }}"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ group }}"

#Stickers
- name: Create Stickers Data Folder
  file:
    path: "{{ stickers-path }}"
    state: directory

- name: Clone a Stickerpicker repository
  git:
    repo: https://github.com/Igeljaeger/stickerpicker.git
    dest: "{{ stickers-path }}"
    clone: yes
    update: yes

- name: Recursively change ownership of a Stickers directory
  ansible.builtin.file:
    path: "{{ stickers-path }}"
    state: directory
    recurse: yes
    owner: "{{ user }}"
    group: "{{ group }}"

#Docker
- name: Create homepage folder
  file:
    path: "{{ compose_folder }}"
    state: directory

- name: Create bibliogram folder
  file:
    path: "{{ bibliogram-path }}"
    state: directory

- name: Clone a bibliogram repository
  git:
    repo: https://git.sr.ht/~cadence/bibliogram
    dest: "{{ bibliogram-path }}"
    clone: yes
    update: yes

- name: Install the package "docker.io"
  apt:
    name: docker.io
    state: present

- name: Install the package "docker-compose"
  apt:
    name: docker-compose
    state: present

- name: Enable docker service
  ansible.builtin.service:
    name: docker
    enabled: yes

- name: Start docker service, if not started
  ansible.builtin.service:
    name: docker
    state: started

- name: Create Navidrome Data Folder
  file:
    path: "/home/{{ user }}/navidrome/"
    state: directory

- name: Create Navidrome Music Folder
  file:
    path: "/home/{{ user }}/navidrome/music"
    state: directory

- name: Deploy Docker-Compose Files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items:
    - { src: "navidrome-compose.yml.j2", dest: "{{ compose_folder }}/navidrome-compose.yml"}

#run docker-compose up -d in the respective paths (see above and in the vars file for reference)